Using Bootstrap to Clone Newsweek page
afcastaneda223/Newsweek-Clone-Using-Bootstrap pull request #5
Opened 2020-02-13 05:17 UTC by afcastaneda223

Using Bootstrap to Clone Newsweek page

2020-02-13 09:43 UTC, rOluochKe requested changes
Hello @afcastaneda223 
### Good job for this far you have come :clap: However, there are changes you need to make.
- Write a more descriptive pull request [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- In the top story section, make the height of the content to equal content on the left and right by defining its height and making it scrollable, repeat this on other screens too
![overlapping](https://user-images.githubusercontent.com/8114528/74420034-d9b91f80-4e5b-11ea-9324-6bfae9a1b209.PNG)
- On mobile screen, your content is going full width, add some padding or margin, make it same with the other content, refer image below.
![mobile](https://user-images.githubusercontent.com/8114528/74420390-6bc12800-4e5c-11ea-8bfb-a4d6bc59da5a.PNG)
- Avoid too much nesting in your html code, you can achieve this in bootstrap easily by defining row and columns
![nesting](https://user-images.githubusercontent.com/8114528/74420745-fefa5d80-4e5c-11ea-9c35-8f8ead5cb609.PNG)

- Make these changes and resubmit for a code review. I wish you all the best
- Happy coding!
- For assistance: Contact me on @rOluochKe

2020-02-13 18:06 UTC, nikasulo requested changes
# Great job @afcastaneda223 !
You have done really nicely and your project is coming together nicely! :clap: Please consider my comments below, make the necessary adjustments and request another review :100: I wish you all the best :smile: 

#### Navigation bar
Your navigation bar is a little buggy, the positioning of elements, and padding of the navigation are in a little twist. Consider comparing what the original site looks like(including but not limited to responsiveness) to yours and make any appropriate changes. 

##### What your navbar looks like on mobile
![screenshot](https://images2.imgbox.com/c2/4f/RhmLrYhK_o.png)

#### [OPTIONAL] Scrollbar
Please consider removing the scroll bar on the center section of the page, I understand the original has some sort of sticky effect and venturing into that or learning about it is something I'll encourage, however, it isn't necessary to replicate the effect and even more so if it will take some polish off your project. Please consider removing the overflow properties you have set on that section, let the full height show, it is completely okay.
![screenshot](https://images2.imgbox.com/79/2a/7ppBx8To_o.png)


#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

##### What's happening
![screenshot](https://images2.imgbox.com/55/8d/FNbSpGJ1_o.gif)

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-13 21:06 UTC, mosesogwo requested changes
**Hi @afcastaneda223, you are getting there:+1:. Let's address the following:**
1. Our navbar should fill at least 95% of the header width.
![image](https://user-images.githubusercontent.com/46611870/74477134-034d6780-4eab-11ea-97b4-66c3508cdd33.png)

2. Give article titles a bold font weight.

3. Reduce font-sizes for these sections:
![image](https://user-images.githubusercontent.com/46611870/74477498-aef6b780-4eab-11ea-853b-e26049e7cc75.png)
The current font-size seems too big when compared with the original site and it causes a distortion on the right-most column at certain widths on medium screen.

4. You have one html validation error that has cropped up. Check it and fix it.

_**Kindly make these adjustments and submit another code review request.**_

**Cheers:stars:**

2020-02-14 05:17 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-02-14 05:45 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @afcastaneda223, 😄 you did a great job implementing some of the changes requested by the previous reviewers. 💯  Your project is very responsive 👍 , However, we still have some requirements left out. Find comments below:
- The nav should look like the original since it is a clone. Currently, this is how the nav looks like. Consider the extra spacing behind the search button
![newnav](https://user-images.githubusercontent.com/46388113/74503976-99ed4900-4eea-11ea-853f-8623907ff3cd.PNG)
```Original```
![newnav1](https://user-images.githubusercontent.com/46388113/74503997-a5d90b00-4eea-11ea-9bf3-456a7db18a12.PNG)
- The footer should have links, currently, we do not have links in the footer.
[OPTIONAL]
```Tablet mode``` Currently, in Culture and travel this is how it looks
![cul](https://user-images.githubusercontent.com/46388113/74504652-cb671400-4eec-11ea-88ee-f90ac205c1fb.PNG)
```Original```
![cul1](https://user-images.githubusercontent.com/46388113/74504661-d621a900-4eec-11ea-9c0c-87c30e4093db.PNG)

Kindly make these changes and submit another code review 🙂 
Happy coding 💻 
Daniel Larbi Addo

2020-02-14 05:45 UTC, addod19 commented on index.html
> +                                        <a href="#">Goody B
Kindly wrap all ```<li>``` with ```<a>```
![newlinks](https://user-images.githubusercontent.com/46388113/74504369-df5e4600-4eeb-11ea-8621-fce5163cb23a.PNG)

2020-02-14 17:32 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-02-14 17:45 UTC, kobiyoyo requested changes
## Hi @afcastaneda223      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there is one more thing required. 
### General
- [ ] Lets give the nav links **Padding** at the **Top**
![1](https://user-images.githubusercontent.com/23278161/74554339-9e9d1600-4f59-11ea-84ca-7293c51caf3d.png)

.



 

### Make changes and submit another code review request.
*Happy coding*

2020-02-14 19:49 UTC, pelzolga123 approved these changes
Approved.

2020-02-14 19:49 UTC, pelzolga123 commented
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

2020-02-14 20:42 UTC, merged